/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MarkappointmentImport } from './routes/mark_appointment'
import { Route as LoginImport } from './routes/login'
import { Route as AppointmentsImport } from './routes/appointments'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MarkappointmentRoute = MarkappointmentImport.update({
  path: '/mark_appointment',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentsRoute = AppointmentsImport.update({
  path: '/appointments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/appointments': {
      preLoaderRoute: typeof AppointmentsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/mark_appointment': {
      preLoaderRoute: typeof MarkappointmentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppointmentsRoute,
  LoginRoute,
  MarkappointmentRoute,
])

/* prettier-ignore-end */
